name: run-tests

on:
  push:
    branches:
      - v1
      - main
  pull_request:
    branches:
      - v1
      - main
  schedule:
    - cron: "0 9 1 * *"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go:
          - 1.18
          - 1.19
        clickhouse:
          - 22.3
          - 22.5
          - 22.6
          - 22.7
          - 22.8
          - latest
    steps:
      - uses: actions/checkout@main

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.5
        with:
          stable: false
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          CLICKHOUSE_SERVER=${{ matrix.clickhouse }} make test
